server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chengkenny/cloud-example-config.git  # 配置git仓库的地址
          search-paths: dev                                            # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: cheng_kenny@163.com                                # git仓库的账号
          password: mxy322512                                          # git仓库的密码
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      #      defaultZone: http://localhost:8761/eureka/                       # 本地注册中心eurka地址
      defaultZone: http://111.229.16.133:8761/eureka/                  # 腾讯云注册中心eurka地址

