spring:
  application:
    name: eureka-server-cluster
  profiles:
    active: eureka-server-01
---
spring:
  profiles: eureka-server-01
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    registerWithEureka: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/

---
spring:
  profiles: eureka-server-02
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    registerWithEureka: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
---
spring:
  profiles: eureka-server-03
server:
  port: 8763
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    registerWithEureka: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
